### PR TITLE
2016-03-16-test-staging-trigger.md

### PR DESCRIPTION
**Pull request by literarymachine**
This pull request should trigger the build of the `pages-staging` branch.

### CODE REVIEW

**Comment by anarchivist** [comment]
It looks like the push is failing - let me check to make sure the account has the right privileges on this repository.

**Comment by literarymachine** [comment]
The exit code of the build is ok: https://travis-ci.org/rightsstatements/rightsstatements.github.io/builds/116408928, and the previous merge to master triggered the build of [pages-production](https://github.com/rightsstatements/rightsstatements.github.io/tree/pages-production) as it was supposed to. I don't think this is a permission error, but I can't quite see why `pages-staging` is not being added.

**Comment by literarymachine** [comment]
Sorry, I was referring to an older build. As it seems, all is well; [pages-staging](https://github.com/rightsstatements/rightsstatements.github.io/tree/pages-staging) was created by this PR,  [pages-production](https://github.com/rightsstatements/rightsstatements.github.io/tree/pages-production) was updated by your merge.

**Comment by anarchivist** [comment]
Yes, there was an issue with the permission scope on the access token, which I've now fixed.

**Comment by literarymachine** [comment]
Excellent. The automatic push of the binary build of rights-app to a newly tagged release is also working: https://github.com/rightsstatements/rights-app/releases/tag/v0.2.0.

**Pull request merged**
