### PR TITLE
Update documentation with deployment instructions

### LINKED ISSUE #11: Document editorial workflow for site content
From the minutes: "Allowing to edit the master branch, which automatically updates rightsstatements.github.io. Consequently we use rightsstatements.github.io as our staging environment."

### PR DESCRIPTION
**Pull request by literarymachine**
Fixes #11

### CODE REVIEW

**Comment by anarchivist** [comment]
@literarymachine The documentation looks fine to me - is there a blocker, or will Apache be able to proxy `localhost:8080` without going through Conostix's proxy?

**Comment by literarymachine** [comment]
> is there a blocker

As long as it is ok to view the GitHub Pages automatic build of the staging site only via http://rightsstatements.github.io/ and not via http://rights-stg.rightsstatements.org/ there is no blocker:

    Staging site: http://rightsstatements.github.io/
    Staging app: http://rights-stg.rightsstatements.org/vocab/1.0/ -> (no-conostix-proxy) -> http://localhost:9000/vocab/1.0/

Of course, we could set up a redirection:

    Staging site: http://rights-stg.rightsstatements.org/ -> HTTP 301 -> http://rightsstatements.github.io/
    Staging app: http://rights-stg.rightsstatements.org/vocab/1.0/ -> (no-conostix-proxy) -> http://localhost:9000/vocab/1.0/

Deploying the build of the staging site to http://rights-stg.rightsstatements.org/ works, too:

    Staging site: http://rights-stg.rightsstatements.org/ -> (no-conostix-proxy)-> http://localhost:8080/
    Staging app: http://rights-stg.rightsstatements.org/vocab/1.0/ -> (no-conostix-proxy) -> http://localhost:9000/vocab/1.0/

The problem is only this combination, because Apache refuses to use the remote proxy only for the site, but not for the app:

    Staging site: http://rights-stg.rightsstatements.org/ -> conostix-proxy -> http://rightsstatements.github.io/
    Staging app: http://rights-stg.rightsstatements.org/vocab/1.0/ -> (no-conostix-proxy) -> http://localhost:9000/vocab/1.0/

This could easily be solved by allowing connections to `localhost` via the conostix proxy and then sending both connections through it:

    Staging site: http://rights-stg.rightsstatements.org/ -> conostix-proxy -> http://rightsstatements.github.io/
    Staging app: http://rights-stg.rightsstatements.org/vocab/1.0/ -> conostix-proxy -> http://localhost:9000/vocab/1.0/

In my eyes, this would be the correct solution anyways because in case we ever move the proxy, the app and the site to separate servers, the corresponding connections would obviously have to be whitelisted.

Since the production site is deployed on `localhost:8080` in the current setup anyways, the above does not apply to it.

**Comment by anarchivist** [comment]
>As long as it is ok to view the GitHub Pages automatic build of the staging site only via http://rightsstatements.github.io/ and not via http://rights-stg.rightsstatements.org/ there is no blocker:
>
```
Staging site: http://rightsstatements.github.io/ 
Staging app: http://rights-stg.rightsstatements.org/vocab/1.0/ -> (no-conostix-proxy) -> http://localhost:9000/vocab/1.0/
```
> [...]
> Deploying the build of the staging site to http://rights-stg.rightsstatements.org/ works, too:
>
```
Staging site: http://rights-stg.rightsstatements.org/ -> (no-conostix-proxy)-> http://localhost:8080/
Staging app: http://rights-stg.rightsstatements.org/vocab/1.0/ -> (no-conostix-proxy) -> http://localhost:9000/vocab/1.0/
```

My inclination would be one of these two options, or a combination of them. I think having the preview on rightsstatements.github.io works well enough if working group members want to preview the changes without running a deployment. I'd recommend avoiding going through the Conostix proxy just because of the lead time it's taken for them to resolve our issues. Does that make sense? What do you think?

**Comment by literarymachine** [comment]
> Does that make sense? What do you think?

I would definitely favor the first approach, i.e. using only http://rightsstatements.github.io for staging. This is why we chose this approach in the first place, just wanted to make sure we are on the same page here. Updated the README accordingly.

**Comment by anarchivist** [comment]
OK - that sounds fine to me. Thanks @literarymachine.

**Pull request merged**
