### PR TITLE
Initial implementation of templates

### PR DESCRIPTION
**Pull request by j0hj0h**

### CODE REVIEW

**Comment by literarymachine** [comment]
Deployed to http://h2481931.stratoserver.net:4000/

@anarchivist Could you also whitelist that server for the font?

**Comment by anarchivist** [comment]
@literarymachine Yep, just whitelisted.

**Comment by literarymachine** [comment]
@anarchivist Thanks. It is currently not being picked up, but that does not seem to be a matter of permission. Will look into that.

**Comment by anarchivist** [comment]
@literarymachine According to the configuration for Typography.com, we need to specify the font as follows in CSS (presumably in development mode): `font-family: "Gotham SSm A", "Gotham SSm B";`

**Comment by literarymachine** [comment]
> font-family: "Gotham SSm A", "Gotham SSm B";

Now this is odd. It is precisely what we had when we encountered https://github.com/rightsstatements/rightsstatements.github.io/issues/6#issuecomment-205403453, which we fixed by simply using "Gotham". Anyhow, fixed on [dev](http://h2481931.stratoserver.net:4000/) now.

**Comment by literarymachine** [comment]
@anarchivist: Could you also whitelist http://rightsstatements.github.io/ for the font?

**Comment by anarchivist** [comment]
@literarymachine Done.

**Comment by literarymachine** [comment]
Sorry @anarchivist, please ignore that. Not seeing the forest for the trees.

**Comment by literarymachine** [comment]
LOL - thanks. I thought it already was because it suddenly worked after a reload.

**Pull request merged**
