### PR TITLE
Layout fixes

### LINKED ISSUE #45: Homepage: Remove the line break before "find out more about…"

### PR DESCRIPTION
**Pull request by literarymachine**
On dev: http://h2481931.stratoserver.net:4000/

Fixes #45, #44, #43, #42, #41, #38, #35, #32, #26, #6.

Regarding #37, the logos are properly placed in a grid. They have very different image sizes, with e.g. the Europeana logo having much more empty space on top than the DPLA one. We should probably fix this by cropping the images accordingly.

Regarding #41, @j0hj0h adjusted the font sizes by rule of thumb because we did not receive any input on what the exact sizes should be.

### CODE REVIEW

**Comment by anarchivist** [comment]
Re: #38 - the heading associated with the anchor ends up displaying under the navigation bar after clicking:

**Comment by anarchivist** [comment]
A few minor issues that relate to responsiveness. Here's the About page on an emulated iPhone 6 screen (note the header): 

screen shot 2016-04-28 at 12 35 43 pm

Two issues on the HTML representation of the vocab (see URIs) - visibly clipped in one, and a seemingly forced linebreak in the second following a hyphen. Again, both on an emulated iPhone 6:

screen shot 2016-04-28 at 12 36 30 pm

screen shot 2016-04-28 at 12 36 50 pm

**Comment by anarchivist** [comment]
Other than these two issues I think this looks good.

**Comment by anarchivist** [comment]
@ryanjunell - can you look at the results of this with an eye to #41?

**Comment by literarymachine** [comment]
On dev. Regarding https://github.com/rightsstatements/rightsstatements.github.io/pull/46#issuecomment-215484618 please note that the headings might appear to be pushed down too far on non-production. This is due to the warning attached to the sticky header.

**Comment by j0hj0h** [comment]
Headlines disappearing behind header:
@literarymachine is right, it's because of the warning

Unwrapped Headline:
Consider to put a softhyphen between syllables of long headline words. It's available as HTML entity `&shy;`

Unwrapped URLs:
Can be fixed by css `word-wrap` property and it's vendor prefixed siblings. See:
http://stackoverflow.com/questions/18157620/responsive-solution-for-long-urls-that-exceed-the-device-width
https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/

**Comment by anarchivist** [comment]
Thanks @j0hj0h - this looks good to me, and I appreciate the recommendations.

**Pull request merged**
